import { Chess } from 'chess.js';
import type { Move } from 'chess.js';
import { clone, distance, pieceSquares, xy } from './chessUtils';
import { rankMoves } from './boundedSearch';

export interface EndgameTechniqueProof { family: string; ruleSentence: string; relevantSquares: string[]; beforeMetric: number; afterMetric: number; searchDepth: number; bestScore: number; nextBestScore: number; principalVariation: string[]; proceduralChecks: string[]; }
export function analyzeTechnique(chess: Chess, move: Move, family: string, depth = 7): EndgameTechniqueProof {
  const after = clone(chess); after.move(move); const side = move.color; const pawn = pieceSquares(chess, side, 'p')[0]; const ownKing = pieceSquares(chess, side, 'k')[0]; const enemyKing = pieceSquares(chess, side === 'w' ? 'b' : 'w', 'k')[0]; const ranks = rankMoves(chess, depth); const selected = ranks.find((r) => r.move.from === move.from && r.move.to === move.to) ?? ranks[0];
  const beforeMetric = pawn ? distance(ownKing, pawn) - distance(enemyKing, pawn) : 0; const afterKing = pieceSquares(after, side, 'k')[0]; const afterPawn = pieceSquares(after, side, 'p')[0]; const afterEnemy = pieceSquares(after, side === 'w' ? 'b' : 'w', 'k')[0]; const afterMetric = afterPawn ? distance(afterKing, afterPawn) - distance(afterEnemy, afterPawn) : beforeMetric;
  const rules: Record<string, string> = { rook_behind_passer: 'Place the rook behind the passed pawn so its support grows as the pawn advances.', king_cutoff: 'Use the rook to cut the defending king away from the promotion zone.', active_king: 'Centralize the king before spending pawn tempi.', lucena_bridge: 'Build a rook bridge so side checks can be blocked.', philidor_defense: 'Keep the rook on the third rank until the pawn advances, then check from behind.', opposition: 'Take or yield opposition according to whose turn creates the entry square.' };
  return { family, ruleSentence: rules[family] ?? 'Improve the active endgame piece while preserving the conversion geometry.', relevantSquares: [move.from, move.to, pawn, ownKing, enemyKing].filter(Boolean), beforeMetric, afterMetric, searchDepth: depth, bestScore: selected?.score ?? 0, nextBestScore: ranks.find((r) => r.move.from !== move.from || r.move.to !== move.to)?.score ?? 0, principalVariation: selected?.pv ?? [], proceduralChecks: ['legal named-family construction', 'kings non-adjacent', 'bounded move-tree reviewed', `piece count ${chess.board().flat().filter(Boolean).length}`] };
}
