import fs from "node:fs";
import path from "node:path";
import { Chess } from "chess.js";

type BuiltEntry = {
  eco: string;
  name: string;
  uciKey: string;
  ply: number;
  familyName: string;
  variationName: string | null;
};

const REPO_ROOT = process.cwd();
const INPUT_DIR = path.join(REPO_ROOT, "imports", "openings", "lichess");
const OUTPUT_PATH = path.join(REPO_ROOT, "lib", "blundr", "openings", "lichessOpeningIdentity.generated.ts");
const SOURCE_FILES = ["a.tsv", "b.tsv", "c.tsv", "d.tsv", "e.tsv"];

// Keep this display-only identity dataset small.
// Stage 2 runtime training is 12 ply, so deeper ultra-specific theory names are not needed in the browser.
const MAX_IDENTITY_PLY = 12;

function stripSanAnnotation(san: string): string {
  return san.trim().replace(/[!?]+$/g, "");
}

function pgnToUciSequence(pgn: string): string[] {
  const game = new Chess();
  const tokens = pgn
    .replace(/\{[^}]*\}/g, " ")
    .replace(/\([^)]*\)/g, " ")
    .split(/\s+/)
    .map((token) => token.trim())
    .filter(Boolean)
    .filter((token) => !/^\d+\.(\.\.)?$/.test(token))
    .filter((token) => !/^(1-0|0-1|1\/2-1\/2|\*)$/.test(token));

  const uci: string[] = [];

  for (const rawToken of tokens) {
    const san = stripSanAnnotation(rawToken.replace(/^\d+\.\.\./, "").replace(/^\d+\./, ""));
    if (!san) continue;

    const move = game.move(san);
    if (!move) {
      throw new Error(`invalid_pgn_san:${pgn}:${rawToken}`);
    }

    uci.push(`${move.from}${move.to}${move.promotion ?? ""}`.toLowerCase());

    if (uci.length > MAX_IDENTITY_PLY) break;
  }

  return uci;
}

function splitOpeningName(name: string): { familyName: string; variationName: string | null } {
  const [family, ...rest] = name.split(":");
  const familyName = family.trim();
  const variationName = rest.join(":").trim();
  return {
    familyName,
    variationName: variationName.length > 0 ? variationName : null,
  };
}

function readTsv(filePath: string): BuiltEntry[] {
  const text = fs.readFileSync(filePath, "utf8");
  const lines = text.split(/\r?\n/).filter(Boolean);
  const rows = lines.slice(1);
  const entries: BuiltEntry[] = [];

  for (const row of rows) {
    const [ecoRaw, nameRaw, pgnRaw] = row.split("\t");
    const eco = String(ecoRaw ?? "").trim();
    const name = String(nameRaw ?? "").trim();
    const pgn = String(pgnRaw ?? "").trim();

    if (!eco || !name || !pgn) continue;

    const uci = pgnToUciSequence(pgn);
    if (!uci.length || uci.length > MAX_IDENTITY_PLY) continue;

    const { familyName, variationName } = splitOpeningName(name);

    entries.push({
      eco,
      name,
      uciKey: uci.join(","),
      ply: uci.length,
      familyName,
      variationName,
    });
  }

  return entries;
}

const STAGE2_RELEVANT_FAMILY_PATTERNS = [
  /Italian Game/i,
  /Caro-Kann Defense/i,
  /French Defense/i,
  /Sicilian Defense/i,
  /Queen's Indian Defense/i,
  /Nimzo-Indian Defense/i,
  /Queen's Gambit/i,
  /Slav Defense/i,
  /King's Indian Defense/i,
  /London System/i,
  /Colle System/i,
  /Ruy Lopez/i,
  /Scotch Game/i,
  /Vienna Game/i,
  /Petrov|Petroff/i,
  /Pirc Defense/i,
  /Scandinavian Defense/i,
  /English Opening/i,
  /Réti Opening|Reti Opening/i,
  /Catalan Opening/i,
  /Indian Defense/i,
];

function isStage2Relevant(entry: BuiltEntry): boolean {
  return STAGE2_RELEVANT_FAMILY_PATTERNS.some((pattern) => pattern.test(entry.name));
}

const entries = SOURCE_FILES
  .flatMap((filename) => readTsv(path.join(INPUT_DIR, filename)))
  .filter(isStage2Relevant);

// Deduplicate by UCI key. Prefer the shorter/base name if multiple names map to the same sequence.
const byUci = new Map<string, BuiltEntry>();
for (const entry of entries) {
  const existing = byUci.get(entry.uciKey);
  if (!existing) {
    byUci.set(entry.uciKey, entry);
    continue;
  }

  const existingSpecificity = existing.name.split(":").length + existing.name.split(",").length;
  const nextSpecificity = entry.name.split(":").length + entry.name.split(",").length;
  if (nextSpecificity < existingSpecificity) {
    byUci.set(entry.uciKey, entry);
  }
}

const deduped = Array.from(byUci.values()).sort((a, b) => {
  if (a.ply !== b.ply) return b.ply - a.ply;
  return a.name.localeCompare(b.name);
});

const output = `// Generated by scripts/blundr/buildLichessOpeningIdentityManifest.ts.
// Source: lichess-org/chess-openings TSV files.
// Display-only opening identity data. Never use this file for move authority.

export type LichessOpeningIdentityEntry = {
  eco: string;
  name: string;
  uciKey: string;
  ply: number;
  familyName: string;
  variationName: string | null;
};

export const LICHESS_OPENING_IDENTITY_MAX_PLY = ${MAX_IDENTITY_PLY};

export const LICHESS_OPENING_IDENTITY_MANIFEST: LichessOpeningIdentityEntry[] = ${JSON.stringify(deduped, null, 2)};

export const LICHESS_OPENING_IDENTITY_MANIFEST_COUNT = ${deduped.length};
`;

fs.writeFileSync(OUTPUT_PATH, output);
console.log(`wrote ${deduped.length} lean opening identity entries to ${path.relative(REPO_ROOT, OUTPUT_PATH)}`);
