import fs from "node:fs";
import path from "node:path";
import { Chess } from "chess.js";

type BuiltEntry = {
  eco: string;
  name: string;
  pgn: string;
  uci: string[];
  ply: number;
  familyName: string;
  variationName: string | null;
};

const REPO_ROOT = process.cwd();
const INPUT_DIR = path.join(REPO_ROOT, "imports", "openings", "lichess");
const OUTPUT_PATH = path.join(REPO_ROOT, "lib", "blundr", "openings", "lichessOpeningIdentity.generated.ts");
const SOURCE_FILES = ["a.tsv", "b.tsv", "c.tsv", "d.tsv", "e.tsv"];

function stripSanAnnotation(san: string): string {
  return san.trim().replace(/[!?]+$/g, "");
}

function pgnToUciSequence(pgn: string): string[] {
  const game = new Chess();
  const tokens = pgn
    .replace(/\{[^}]*\}/g, " ")
    .replace(/\([^)]*\)/g, " ")
    .split(/\s+/)
    .map((token) => token.trim())
    .filter(Boolean)
    .filter((token) => !/^\d+\.(\.\.)?$/.test(token))
    .filter((token) => !/^(1-0|0-1|1\/2-1\/2|\*)$/.test(token));

  const uci: string[] = [];

  for (const rawToken of tokens) {
    const san = stripSanAnnotation(rawToken.replace(/^\d+\.\.\./, "").replace(/^\d+\./, ""));
    if (!san) continue;

    const move = game.move(san);
    if (!move) {
      throw new Error(`invalid_pgn_san:${pgn}:${rawToken}`);
    }

    uci.push(`${move.from}${move.to}${move.promotion ?? ""}`.toLowerCase());
  }

  return uci;
}

function splitOpeningName(name: string): { familyName: string; variationName: string | null } {
  const [family, ...rest] = name.split(":");
  const familyName = family.trim();
  const variationName = rest.join(":").trim();
  return {
    familyName,
    variationName: variationName.length > 0 ? variationName : null,
  };
}

function readTsv(filePath: string): BuiltEntry[] {
  const text = fs.readFileSync(filePath, "utf8");
  const lines = text.split(/\r?\n/).filter(Boolean);
  const rows = lines.slice(1);
  const entries: BuiltEntry[] = [];

  for (const row of rows) {
    const [ecoRaw, nameRaw, pgnRaw] = row.split("\t");
    const eco = String(ecoRaw ?? "").trim();
    const name = String(nameRaw ?? "").trim();
    const pgn = String(pgnRaw ?? "").trim();

    if (!eco || !name || !pgn) continue;

    const uci = pgnToUciSequence(pgn);
    if (!uci.length) continue;

    const { familyName, variationName } = splitOpeningName(name);

    entries.push({
      eco,
      name,
      pgn,
      uci,
      ply: uci.length,
      familyName,
      variationName,
    });
  }

  return entries;
}

const entries = SOURCE_FILES.flatMap((filename) => readTsv(path.join(INPUT_DIR, filename)));

const deduped = Array.from(
  new Map(entries.map((entry) => [`${entry.uci.join(",")}::${entry.name}`, entry])).values(),
).sort((a, b) => {
  if (a.uci.length !== b.uci.length) return b.uci.length - a.uci.length;
  return a.name.localeCompare(b.name);
});

const output = `// Generated by scripts/blundr/buildLichessOpeningIdentityManifest.ts.
// Source: lichess-org/chess-openings TSV files.
// Display-only opening identity data. Never use this file for move authority.

export type LichessOpeningIdentityEntry = {
  eco: string;
  name: string;
  pgn: string;
  uci: readonly string[];
  ply: number;
  familyName: string;
  variationName: string | null;
};

export const LICHESS_OPENING_IDENTITY_MANIFEST = ${JSON.stringify(deduped, null, 2)} as const satisfies readonly LichessOpeningIdentityEntry[];

export const LICHESS_OPENING_IDENTITY_MANIFEST_COUNT = ${deduped.length} as const;
`;

fs.writeFileSync(OUTPUT_PATH, output);
console.log(`wrote ${deduped.length} opening identity entries to ${path.relative(REPO_ROOT, OUTPUT_PATH)}`);
