import type { CoachBenchmarkFixture } from "./coachBenchmarkTypes";

const START = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -";
const ITALIAN_BC4 = "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq -";
const ITALIAN_C3 = "r1bqk2r/ppp2ppp/2np1n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq -";

function inBookBase(id: string, title: string, conceptId: string, patternId: string, moveUci?: string, moveSan?: string): CoachBenchmarkFixture {
  return {
    id,
    title,
    fen: ITALIAN_BC4,
    normalizedFen: ITALIAN_BC4,
    sideToMove: "w",
    moveHistorySan: ["e4", "e5", "Nf3", "Nc6"],
    viewMode: "assisted",
    bookStatus: "in_book",
    userState: {
      attempts: 0,
      wrongAttempts: 0,
      hintUsed: false,
      answerShown: false,
      elapsedMs: 4000,
      priorPatternMisses: 0,
      priorPatternSuccesses: 1,
      weakConcepts: [],
    },
    visualRecipeFixture: {
      conceptId,
      patternId,
      moveUci,
      moveSan,
      keySquares: ["f1", "c4", "f7"],
      keyPieces: ["bishop"],
      primitiveTypes: ["move_arrow", "pressure_line", "target_ring"],
      frameMatches: true,
      fenMatches: true,
    },
    expected: {
      allowedCoachModes: ["assisted_teach", "plain_prompt", "plain_hint", "plain_answer_revealed"],
      exactMoveAllowed: true,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: false,
      forbiddenTerms: ["stockfish", "top two", "verified_top2"],
    },
  };
}

export const COACH_BENCHMARK_FIXTURES: CoachBenchmarkFixture[] = [
  {
    ...inBookBase("italian_start_e4_assisted", "Italian start e4 assisted", "development", "italian:e4", "e2e4", "e4"),
    expected: {
      allowedCoachModes: ["assisted_teach"],
      exactMoveAllowed: true,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: false,
      forbiddenTerms: ["stockfish", "top two"],
    },
  },
  {
    ...inBookBase("italian_bishop_pressure_assisted", "Italian bishop pressure assisted", "develop_with_pressure", "italian:bc4_f7", "f1c4", "Bc4"),
    expected: {
      allowedCoachModes: ["assisted_teach"],
      exactMoveAllowed: true,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: false,
      requiredConcepts: ["develop_with_pressure"],
      requiredObjects: ["bishop", "f7"],
      forbiddenTerms: ["stockfish", "top two"],
    },
  },
  {
    ...inBookBase("italian_c3_plain_prompt", "Italian c3 plain prompt", "prepare_center_break", "italian:c3_d4", "c2c3", "c3"),
    viewMode: "plain",
    fen: ITALIAN_C3,
    normalizedFen: ITALIAN_C3,
    expected: {
      allowedCoachModes: ["plain_prompt"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: true,
      shouldShowPlanButton: false,
      forbiddenTerms: ["stockfish", "top two", "c3"],
    },
  },
  {
    ...inBookBase("italian_c3_wrong_once", "Italian c3 wrong once", "prepare_center_break", "italian:c3_d4", "c2c3", "c3"),
    viewMode: "plain",
    fen: ITALIAN_C3,
    normalizedFen: ITALIAN_C3,
    userState: { attempts: 1, wrongAttempts: 1, hintUsed: false, answerShown: false, elapsedMs: 12000, priorPatternMisses: 1, priorPatternSuccesses: 0, weakConcepts: ["prepare_center_break"] },
    expected: {
      allowedCoachModes: ["plain_hint", "plain_wrong_move"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: true,
      shouldShowPlanButton: false,
      forbiddenTerms: ["stockfish", "top two", "Play c3"],
    },
  },
  {
    ...inBookBase("castle_for_safety_assisted", "Castle for safety assisted", "castle_for_safety", "italian:castle", "e1g1", "O-O"),
    expected: {
      allowedCoachModes: ["assisted_teach"],
      exactMoveAllowed: true,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: false,
      requiredObjects: ["king", "center"],
      forbiddenTerms: ["stockfish", "top two"],
    },
  },
  {
    ...inBookBase("rook_to_center_re1_conservative", "Re1 conservative", "rook_to_center", "italian:re1", "f1e1", "Re1"),
    expected: {
      allowedCoachModes: ["assisted_teach"],
      exactMoveAllowed: true,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: false,
      forbiddenTerms: ["fork", "pin", "skewer", "stockfish"],
    },
  },
  {
    ...inBookBase("center_tension_context", "Center tension context", "center_tension", "italian:center"),
    expected: {
      allowedCoachModes: ["assisted_teach", "plain_prompt"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: false,
      forbiddenTerms: ["play", "stockfish"],
    },
  },
  {
    id: "out_of_book_transition",
    title: "Out of book transition",
    fen: START,
    normalizedFen: START,
    sideToMove: "w",
    moveHistorySan: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6"],
    viewMode: "freeplay",
    bookStatus: "book_complete",
    userState: { attempts: 3, wrongAttempts: 0, hintUsed: false, answerShown: false, elapsedMs: 10000, priorPatternMisses: 1, priorPatternSuccesses: 2, weakConcepts: [] },
    expected: {
      allowedCoachModes: ["freeplay_principle", "supported_continuation"],
      allowedLiveOpportunities: ["plan_transition", "supported_continuation", "king_safety_urgent", "center_decision"],
      allowedIntents: ["explain_plan", "nudge", "warn", "ask_question"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: true,
      forbiddenTerms: ["stockfish", "top two", "show answer"],
    },
  },
  {
    id: "out_of_book_center_tension",
    title: "Out of book center tension",
    fen: ITALIAN_C3,
    normalizedFen: ITALIAN_C3,
    sideToMove: "w",
    moveHistorySan: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5"],
    viewMode: "freeplay",
    bookStatus: "out_of_book",
    userState: { attempts: 2, wrongAttempts: 0, hintUsed: false, answerShown: false, elapsedMs: 9000, priorPatternMisses: 1, priorPatternSuccesses: 2, weakConcepts: ["center_tension"] },
    positionFeatureFixture: {
      centerState: "tense",
      kingSafety: "watch_center",
      developmentStatus: "normal",
      leastActivePieces: ["wn@b1"],
      openFiles: [],
      semiOpenFiles: ["e"],
      plausiblePawnBreaks: ["d4"],
      castlingStatus: { white: "uncastled", black: "uncastled" },
      materialTension: "medium",
      pieceCoordinationTags: ["center_tension"],
      tacticalAlert: "none",
    },
    expected: {
      allowedCoachModes: ["freeplay_principle", "supported_continuation"],
      allowedLiveOpportunities: ["center_decision", "pattern_transfer", "king_safety_urgent"],
      allowedIntents: ["ask_question", "explain_plan", "connect_pattern", "warn"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: true,
      forbiddenTerms: ["stockfish", "maia"],
    },
  },
  {
    id: "natural_human_mistake",
    title: "Natural human mistake",
    fen: START,
    normalizedFen: START,
    sideToMove: "w",
    moveHistorySan: [],
    viewMode: "freeplay",
    bookStatus: "out_of_book",
    userState: { attempts: 1, wrongAttempts: 0, hintUsed: false, answerShown: false, elapsedMs: 10000, priorPatternMisses: 0, priorPatternSuccesses: 0, weakConcepts: [] },
    maiaFixture: {
      status: "available",
      source: "mock",
      userElo: 1400,
      opponentElo: 1400,
      topMoves: [{ moveUci: "a2a4", probability: 0.4, rank: 1 }],
      moveProbabilities: { a2a4: 0.4, e2e4: 0.04 },
      entropy: 1.2,
      topMoveProbability: 0.4,
      humanConsensus: "high",
      skillGradients: [],
    },
    engineFixture: {
      status: "available",
      candidates: [
        { moveUci: "a2a4", safety: "mistake", isTopEngineMove: false },
        { moveUci: "e2e4", safety: "safe", isTopEngineMove: true },
      ],
    },
    expected: {
      allowedCoachModes: ["freeplay_principle"],
      allowedLiveOpportunities: ["predictable_human_mistake"],
      allowedIntents: ["warn"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: true,
      forbiddenTerms: ["stockfish", "centipawn", "maia probability"],
    },
  },
  {
    id: "hard_to_find_good_move",
    title: "Hard to find good move",
    fen: START,
    normalizedFen: START,
    sideToMove: "w",
    moveHistorySan: [],
    viewMode: "freeplay",
    bookStatus: "near_book",
    userState: { attempts: 1, wrongAttempts: 0, hintUsed: false, answerShown: false, elapsedMs: 8000, priorPatternMisses: 0, priorPatternSuccesses: 1, weakConcepts: [] },
    maiaFixture: {
      status: "available",
      source: "mock",
      userElo: 1500,
      opponentElo: 1500,
      topMoves: [{ moveUci: "a2a3", probability: 0.2, rank: 1 }],
      moveProbabilities: { a2a3: 0.2, e2e4: 0.03 },
      entropy: 1.8,
      topMoveProbability: 0.2,
      humanConsensus: "medium",
      skillGradients: [],
    },
    engineFixture: {
      status: "available",
      candidates: [
        { moveUci: "a2a3", safety: "inaccuracy", isTopEngineMove: false },
        { moveUci: "e2e4", safety: "best", isTopEngineMove: true },
      ],
    },
    expected: {
      allowedCoachModes: ["freeplay_principle", "supported_continuation"],
      allowedLiveOpportunities: ["hard_to_find_good_move", "supported_continuation"],
      allowedIntents: ["compare_instincts", "explain_plan"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: true,
      forbiddenTerms: ["stockfish", "centipawn"],
    },
  },
  {
    id: "least_active_piece",
    title: "Least active piece",
    fen: START,
    normalizedFen: START,
    sideToMove: "w",
    moveHistorySan: ["d4", "d5", "Nf3", "Nf6"],
    viewMode: "freeplay",
    bookStatus: "out_of_book",
    userState: { attempts: 1, wrongAttempts: 0, hintUsed: false, answerShown: false, elapsedMs: 5000, priorPatternMisses: 0, priorPatternSuccesses: 0, weakConcepts: [] },
    positionFeatureFixture: {
      centerState: "tense",
      kingSafety: "safe",
      developmentStatus: "behind",
      leastActivePieces: ["wb@f1"],
      openFiles: [],
      semiOpenFiles: [],
      plausiblePawnBreaks: ["e4"],
      castlingStatus: { white: "uncastled", black: "uncastled" },
      materialTension: "low",
      pieceCoordinationTags: ["piece_improvement"],
      tacticalAlert: "none",
    },
    expected: {
      allowedCoachModes: ["freeplay_principle"],
      allowedLiveOpportunities: ["least_active_piece", "center_decision", "king_safety_urgent"],
      allowedIntents: ["nudge", "explain_plan", "warn"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: true,
      forbiddenTerms: ["stockfish"],
    },
  },
  {
    id: "king_safety_urgent",
    title: "King safety urgent",
    fen: ITALIAN_C3,
    normalizedFen: ITALIAN_C3,
    sideToMove: "w",
    moveHistorySan: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5"],
    viewMode: "freeplay",
    bookStatus: "out_of_book",
    userState: { attempts: 2, wrongAttempts: 1, hintUsed: true, answerShown: false, elapsedMs: 20000, priorPatternMisses: 2, priorPatternSuccesses: 1, weakConcepts: ["king_safety"] },
    positionFeatureFixture: {
      centerState: "open",
      kingSafety: "exposed",
      developmentStatus: "normal",
      leastActivePieces: ["wr@h1"],
      openFiles: ["e"],
      semiOpenFiles: [],
      plausiblePawnBreaks: ["d4"],
      castlingStatus: { white: "uncastled", black: "castled" },
      materialTension: "high",
      pieceCoordinationTags: ["king_safety"],
      tacticalAlert: "possible",
    },
    expected: {
      allowedCoachModes: ["freeplay_principle"],
      allowedLiveOpportunities: ["king_safety_urgent"],
      allowedIntents: ["warn"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: true,
      forbiddenTerms: ["stockfish"],
    },
  },
  {
    id: "premature_attack_warning",
    title: "Premature attack warning",
    fen: START,
    normalizedFen: START,
    sideToMove: "w",
    moveHistorySan: ["e4", "e5", "Qh5"],
    viewMode: "freeplay",
    bookStatus: "out_of_book",
    userState: { attempts: 2, wrongAttempts: 1, hintUsed: true, answerShown: false, elapsedMs: 13000, priorPatternMisses: 1, priorPatternSuccesses: 0, weakConcepts: ["development"] },
    expected: {
      allowedCoachModes: ["freeplay_principle"],
      allowedLiveOpportunities: ["predictable_human_mistake", "center_decision", "king_safety_urgent"],
      allowedIntents: ["warn", "explain_plan", "ask_question"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: true,
      forbiddenTerms: ["stockfish"],
    },
  },
  {
    id: "pattern_transfer_c3_d4",
    title: "Pattern transfer c3 to d4",
    fen: ITALIAN_C3,
    normalizedFen: ITALIAN_C3,
    sideToMove: "w",
    moveHistorySan: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3"],
    viewMode: "freeplay",
    bookStatus: "near_book",
    userState: { attempts: 4, wrongAttempts: 0, hintUsed: false, answerShown: false, elapsedMs: 6000, priorPatternMisses: 1, priorPatternSuccesses: 3, weakConcepts: ["prepare_center_break"] },
    patternSignalFixture: {
      connectedConcepts: [{ conceptId: "prepare_center_break", strength: 0.9, reason: "d4 support" }],
      weakConceptMatches: ["prepare_center_break"],
      transferOpportunity: true,
      reviewRelevance: 0.8,
    },
    expected: {
      allowedCoachModes: ["freeplay_principle"],
      allowedLiveOpportunities: ["pattern_transfer"],
      allowedIntents: ["connect_pattern"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: true,
      requiredConcepts: ["prepare_center_break"],
      forbiddenTerms: ["stockfish"],
    },
  },
  {
    id: "opponent_human_response",
    title: "Opponent human response",
    fen: ITALIAN_BC4,
    normalizedFen: ITALIAN_BC4,
    sideToMove: "w",
    moveHistorySan: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5"],
    viewMode: "freeplay",
    bookStatus: "near_book",
    userState: { attempts: 1, wrongAttempts: 0, hintUsed: false, answerShown: false, elapsedMs: 7000, priorPatternMisses: 0, priorPatternSuccesses: 1, weakConcepts: [] },
    expected: {
      allowedCoachModes: ["freeplay_principle", "supported_continuation"],
      allowedLiveOpportunities: ["supported_continuation", "center_decision", "king_safety_urgent"],
      allowedIntents: ["explain_plan", "nudge", "warn"],
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: true,
      forbiddenTerms: ["stockfish"],
    },
  },
  {
    id: "silence_low_confidence",
    title: "Silence low confidence",
    fen: START,
    normalizedFen: START,
    sideToMove: "w",
    moveHistorySan: [],
    viewMode: "freeplay",
    bookStatus: "out_of_book",
    userState: { attempts: 0, wrongAttempts: 0, hintUsed: false, answerShown: false, elapsedMs: 2000, priorPatternMisses: 0, priorPatternSuccesses: 0, weakConcepts: [] },
    engineFixture: { status: "pending", candidates: [] },
    expected: {
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: false,
      forbiddenTerms: ["stockfish"],
      shouldStaySilent: true,
    },
  },
  {
    id: "stale_frame_fen",
    title: "Stale frame/fen",
    fen: START,
    normalizedFen: START,
    sideToMove: "w",
    moveHistorySan: [],
    viewMode: "assisted",
    bookStatus: "in_book",
    userState: { attempts: 0, wrongAttempts: 0, hintUsed: false, answerShown: false, elapsedMs: 1000, priorPatternMisses: 0, priorPatternSuccesses: 0, weakConcepts: [] },
    visualRecipeFixture: {
      conceptId: "development",
      patternId: "start",
      moveUci: "e2e4",
      moveSan: "e4",
      keySquares: ["e2", "e4"],
      keyPieces: ["pawn"],
      primitiveTypes: ["move_arrow"],
      frameMatches: false,
      fenMatches: false,
    },
    expected: {
      exactMoveAllowed: false,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: false,
      forbiddenTerms: ["stockfish"],
      shouldStaySilent: true,
    },
  },
  {
    ...inBookBase("repetition_guard", "Repetition guard", "develop_with_pressure", "italian:bc4_f7", "f1c4", "Bc4"),
    expected: {
      allowedCoachModes: ["assisted_teach"],
      exactMoveAllowed: true,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: false,
      forbiddenTerms: ["stockfish"],
    },
  },
  {
    ...inBookBase("raw_label_blocking", "Raw label blocking", "develop_with_pressure", "italian:bc4_f7", "f1c4", "Bc4"),
    expected: {
      allowedCoachModes: ["assisted_teach"],
      exactMoveAllowed: true,
      shouldShowAnswerButton: false,
      shouldShowPlanButton: false,
      forbiddenTerms: ["stockfish", "verified_top2", "engine_close", "moveTrust"],
    },
  },
];
