import { buildDailyConceptDefinitions } from "./dailyConceptTypes";

export const KEY_SQUARE_CONCEPTS = buildDailyConceptDefinitions("key_squares", [
  {
    slug: "weak_square",
    displayName: "Weak Square",
    shortName: "Weak square",
    summary: "A square can no longer be protected by a pawn and becomes a long-term target.",
    whyItMatters: "Weak squares guide piece placement, invasions, and endgame conversions.",
    commonMistakes: ["Ignoring permanent holes", "Only counting material", "Missing the right invasion route"],
    recommendedDifficulty: ["intro", "beginner"],
    tags: ["weakness", "outpost", "invasion"],
  },
  {
    slug: "outpost_square",
    displayName: "Outpost Square",
    shortName: "Outpost",
    summary: "A stable square for a piece that cannot be chased away by pawns.",
    whyItMatters: "Outposts turn space into activity and create lasting pressure on key files and diagonals.",
    commonMistakes: ["Placing the piece too passively", "Missing the supporting pawn", "Allowing a simple pawn chase"],
    recommendedDifficulty: ["intro", "beginner"],
    tags: ["piece_square", "activity", "control"],
  },
  {
    slug: "knight_hole",
    displayName: "Knight Hole",
    shortName: "Knight hole",
    summary: "A square that becomes especially attractive for a knight because enemy pawns cannot challenge it.",
    whyItMatters: "Knight holes often become the centerpiece of a long-term strategic plan.",
    commonMistakes: ["Ignoring the supporting outpost", "Misreading the blockade", "Trading away the wrong knight"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["knight", "outpost", "hole"],
  },
  {
    slug: "opposition_square",
    displayName: "Opposition Square",
    shortName: "Opposition",
    summary: "A square used to measure direct king opposition and keep control of the key route.",
    whyItMatters: "Opposition squares decide king activity, pawn races, and which side can penetrate first.",
    commonMistakes: ["Moving the king too soon", "Ignoring tempo count", "Missing the king lock"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["king", "endgame", "tempo"],
  },
  {
    slug: "king_entry_square",
    displayName: "King Entry Square",
    shortName: "King entry",
    summary: "A square where the king can enter the enemy camp and target pawns or critical squares.",
    whyItMatters: "Entry squares tell you when a king can convert space into a real invasion.",
    commonMistakes: ["Entering without support", "Ignoring opposition", "Missing the timing of the break"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["king", "invasion", "endgame"],
  },
  {
    slug: "promotion_square",
    displayName: "Promotion Square",
    shortName: "Promotion",
    summary: "The final square a pawn must reach to become a new piece.",
    whyItMatters: "Promotion squares define the endgame plan and the route the passed pawn must follow.",
    commonMistakes: ["Racing without support", "Forgetting king cover", "Missing the queening race"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["endgame", "promotion", "race"],
  },
  {
    slug: "promotion_support_square",
    displayName: "Promotion Support Square",
    shortName: "Support square",
    summary: "A square that helps a pawn or piece support the promotion route.",
    whyItMatters: "Support squares prevent blockade and make promotion ideas easier to calculate.",
    commonMistakes: ["Pushing unsupported", "Ignoring the escort piece", "Missing the stop square"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["promotion", "support", "endgame"],
  },
  {
    slug: "blockade_square",
    displayName: "Blockade Square",
    shortName: "Blockade",
    summary: "A square used to stop a pawn advance and freeze the structure.",
    whyItMatters: "Blockades turn dynamic pawn play into static targets and often decide endgames.",
    commonMistakes: ["Not occupying the square fast enough", "Allowing the pawn to advance", "Using the wrong blocker"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["blockade", "endgame", "weakness"],
  },
  {
    slug: "invasion_square",
    displayName: "Invasion Square",
    shortName: "Invasion",
    summary: "A square from which a heavy piece or king can enter the opponent position.",
    whyItMatters: "Invasion squares convert open files and weak ranks into practical pressure.",
    commonMistakes: ["Entering too early", "Missing the second rank", "Ignoring counterplay against the invader"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["rook", "queen", "invasion"],
  },
  {
    slug: "defensive_anchor_square",
    displayName: "Defensive Anchor Square",
    shortName: "Anchor",
    summary: "A stable square used to hold back an invasion or protect the king.",
    whyItMatters: "Anchor squares help the defender consolidate and survive pressure on open lines.",
    commonMistakes: ["Abandoning the anchor too soon", "Choosing a loose square", "Ignoring the enemy break"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["defense", "king_safety", "stability"],
  },
  {
    slug: "critical_pawn_endgame_square",
    displayName: "Critical Pawn Endgame Square",
    shortName: "Critical square",
    summary: "A square that decides whether a pawn endgame wins or draws.",
    whyItMatters: "Critical squares matter in races, triangulation, and king opposition calculations.",
    commonMistakes: ["Counting only moves, not squares", "Ignoring the opposition", "Misjudging the drawing zone"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["endgame", "king", "calculation"],
  },
  {
    slug: "breakthrough_square",
    displayName: "Breakthrough Square",
    shortName: "Breakthrough",
    summary: "A square where a pawn break opens the position and creates a passed pawn.",
    whyItMatters: "Breakthrough squares are how structure turns into tactics and promotion chances.",
    commonMistakes: ["Breaking too late", "Missing the supporting pawn", "Allowing the defender to close the file"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["pawn_break", "passed_pawn", "tactics"],
  },
]);
