import { buildDailyConceptDefinitions } from "./dailyConceptTypes";

export const PAWN_STRUCTURE_CONCEPTS = buildDailyConceptDefinitions("pawn_structures", [
  {
    slug: "open_center",
    displayName: "Open Center",
    shortName: "Open center",
    summary: "Central files and diagonals are open for direct piece contact.",
    whyItMatters: "Open centers make tempo, piece activity, and tactical breaks more important than pawn chains.",
    commonMistakes: ["Treating the center as static", "Trading into a worse king safety picture", "Ignoring piece activity"],
    recommendedDifficulty: ["intro", "beginner"],
    tags: ["center", "files", "activity"],
  },
  {
    slug: "semi_open_file_structure",
    displayName: "Semi-Open File Structure",
    shortName: "Semi-open file",
    summary: "One side has no pawn on a file, but the file is not fully open yet.",
    whyItMatters: "Semi-open files are the main highways for rooks and queens when structure starts to loosen.",
    commonMistakes: ["Leaving rooks passive", "Ignoring file pressure", "Allowing the opponent to claim the file first"],
    recommendedDifficulty: ["intro", "beginner"],
    tags: ["files", "rook_lanes", "pressure"],
  },
  {
    slug: "pawn_chain",
    displayName: "Pawn Chain",
    shortName: "Pawn chain",
    summary: "Pawns protect each other in a forward diagonal chain.",
    whyItMatters: "Chains define space, where the breaks are, and which side gets the better squares.",
    commonMistakes: ["Attacking the wrong base", "Ignoring the chain direction", "Failing to challenge the lever"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["chain", "space", "lever"],
  },
  {
    slug: "locked_center",
    displayName: "Locked Center",
    shortName: "Locked center",
    summary: "The center is fixed by opposing pawns and cannot be opened immediately.",
    whyItMatters: "Locked centers shift the battle to the wings, pawn storms, and maneuvering plans.",
    commonMistakes: ["Forcing central trades too early", "Ignoring wing play", "Misplacing the king before the structure opens"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["center", "maneuvering", "wings"],
  },
  {
    slug: "doubled_pawns",
    displayName: "Doubled Pawns",
    shortName: "Doubled pawns",
    summary: "Two pawns sit on the same file and cannot protect each other laterally.",
    whyItMatters: "Doubled pawns often create weaknesses, but they can also open files and provide central control.",
    commonMistakes: ["Assuming all doubled pawns are bad", "Trading into a worse structure", "Ignoring the open file they create"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["weakness", "files", "structure"],
  },
  {
    slug: "isolated_queen_pawn",
    displayName: "Isolated Queen Pawn",
    shortName: "IQP",
    summary: "A queen pawn stands alone without friendly pawns on adjacent files.",
    whyItMatters: "The IQP creates dynamic activity, but the endgame and blockade plan can punish it hard.",
    commonMistakes: ["Only seeing the weakness", "Missing the activity", "Allowing a simple blockade"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["weakness", "central_pawn", "activity"],
  },
  {
    slug: "backward_pawn",
    displayName: "Backward Pawn",
    shortName: "Backward pawn",
    summary: "A pawn falls behind its neighbors and needs constant protection.",
    whyItMatters: "Backward pawns are often long-term targets on open or semi-open files.",
    commonMistakes: ["Pushing too late", "Not covering the square in front", "Ignoring the file pressure"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["weakness", "file_pressure", "blockade"],
  },
  {
    slug: "hanging_pawns",
    displayName: "Hanging Pawns",
    shortName: "Hanging pawns",
    summary: "Two adjacent pawns have no pawn support from behind or beside them.",
    whyItMatters: "Hanging pawns can be active and central, but they need exact timing and break support.",
    commonMistakes: ["Letting the pair become fixed", "Missing the central break", "Overprotecting and losing activity"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["central_pawns", "activity", "breaks"],
  },
  {
    slug: "pawn_majority",
    displayName: "Pawn Majority",
    shortName: "Pawn majority",
    summary: "One side has more pawns on one wing than the other side.",
    whyItMatters: "A pawn majority is the raw material for a passed pawn and a winning endgame plan.",
    commonMistakes: ["Pushing without a plan", "Ignoring the weaker wing", "Trading away the majority too early"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["endgame", "majority", "passed_pawn"],
  },
  {
    slug: "minority_attack_structure",
    displayName: "Minority Attack Structure",
    shortName: "Minority attack",
    summary: "A smaller pawn group attacks a larger pawn mass to create weaknesses.",
    whyItMatters: "The minority attack creates structural targets and often changes the whole game plan.",
    commonMistakes: ["Attacking too slowly", "Forgetting the target square", "Opening the position for the wrong side"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["attack", "weakness", "queenside"],
  },
  {
    slug: "carlsbad_structure",
    displayName: "Carlsbad Structure",
    shortName: "Carlsbad",
    summary: "A classic queenside pawn structure with a well-known minority-attack plan.",
    whyItMatters: "Carlsbad positions teach long-term structure plans better than almost any other shape.",
    commonMistakes: ["Playing without a plan", "Ignoring the c-file", "Missing the minority attack idea"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["classic", "queenside", "minority_attack"],
  },
  {
    slug: "maroczy_bind",
    displayName: "Maroczy Bind",
    shortName: "Maroczy bind",
    summary: "A clamp on the center restricts pawn breaks and space.",
    whyItMatters: "The bind often gives lasting pressure, but it must be maintained with precision.",
    commonMistakes: ["Letting the bind dissolve", "Ignoring the c-pawn break", "Overextending the clamp"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["clamp", "space", "control"],
  },
  {
    slug: "kingside_fianchetto_structure",
    displayName: "Kingside Fianchetto Structure",
    shortName: "Fianchetto",
    summary: "The kingside pawn cover is shaped around a fianchettoed bishop and long diagonal pressure.",
    whyItMatters: "This structure changes key squares, king safety, and central break timing.",
    commonMistakes: ["Attacking the wrong pawn", "Ignoring the long diagonal", "Letting the king shelter become loose"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["king_safety", "diagonal", "fianchetto"],
  },
  {
    slug: "passed_pawn",
    displayName: "Passed Pawn",
    shortName: "Passed pawn",
    summary: "A pawn has no opposing pawn in front of it on its file or adjacent files.",
    whyItMatters: "Passed pawns are the clearest path to promotion and endgame winning chances.",
    commonMistakes: ["Not supporting the advance", "Promoting too early without calculation", "Ignoring blockade squares"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["endgame", "promotion", "advanced"],
  },
]);
