import { buildDailyConceptDefinitions } from "./dailyConceptTypes";

export const PIECE_IMBALANCE_CONCEPTS = buildDailyConceptDefinitions("piece_imbalances", [
  {
    slug: "bishop_pair",
    displayName: "Bishop Pair",
    shortName: "Bishop pair",
    summary: "One side keeps both bishops while the opponent gives one up.",
    whyItMatters: "The bishop pair often wins long diagonals, especially when the position opens.",
    commonMistakes: ["Trading a bishop too early", "Ignoring the open position", "Letting the knights dominate closed play"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["bishops", "long_diagonal", "activity"],
  },
  {
    slug: "good_bishop_vs_bad_bishop",
    displayName: "Good Bishop vs Bad Bishop",
    shortName: "Good bishop",
    summary: "One bishop has free scope while the other is blocked by its own pawns.",
    whyItMatters: "The better bishop can dominate key squares, even when material is equal.",
    commonMistakes: ["Only counting the bishop type", "Ignoring pawn color", "Trading into the wrong structure"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["bishops", "structure", "scope"],
  },
  {
    slug: "knight_vs_bishop_closed_center",
    displayName: "Knight vs Bishop in a Closed Center",
    shortName: "Knight vs bishop",
    summary: "Closed pawn chains often favor the knight over the bishop.",
    whyItMatters: "Piece choice changes sharply when the center closes and outposts appear.",
    commonMistakes: ["Valuing the bishop too much", "Ignoring outpost squares", "Opening the wrong side of the board"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["minor_pieces", "closed_center", "outpost"],
  },
  {
    slug: "minor_piece_outpost",
    displayName: "Minor Piece Outpost",
    shortName: "Minor outpost",
    summary: "A knight or bishop lands on a secure square and cannot be chased by pawns.",
    whyItMatters: "Minor piece outposts create long-term pressure and tactical chances.",
    commonMistakes: ["Placing the piece too passively", "Ignoring the supporting pawn", "Allowing the enemy break"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["outpost", "minor_pieces", "control"],
  },
  {
    slug: "rook_on_open_file",
    displayName: "Rook on an Open File",
    shortName: "Open file rook",
    summary: "A rook occupies a file with no pawns blocking its path.",
    whyItMatters: "Open files are the main highways for rook pressure and invasion.",
    commonMistakes: ["Leaving the rook behind the pawns", "Allowing the opponent to claim the file", "Ignoring the seventh rank"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["rook", "files", "pressure"],
  },
  {
    slug: "rook_seventh_rank",
    displayName: "Rook on the Seventh Rank",
    shortName: "Seventh rank",
    summary: "A rook reaches the enemy seventh rank and attacks pawns from behind.",
    whyItMatters: "The seventh rank often decides endgames and many tactical middlegame attacks.",
    commonMistakes: ["Not supporting the rook", "Ignoring king cut-off", "Missing the back-rank weaknesses"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["rook", "invasion", "endgame"],
  },
  {
    slug: "queen_activity",
    displayName: "Queen Activity",
    shortName: "Queen activity",
    summary: "The queen has active squares, targets, and tempo options.",
    whyItMatters: "Active queens punish passive development and keep tactical pressure alive.",
    commonMistakes: ["Overtrading the queen too soon", "Ignoring king safety", "Letting the queen become a spectator"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["queen", "activity", "tempo"],
  },
  {
    slug: "space_advantage",
    displayName: "Space Advantage",
    shortName: "Space",
    summary: "One side controls more safe squares and restricts the opponent's pieces.",
    whyItMatters: "Space gives better squares, easier maneuvering, and more freedom to attack.",
    commonMistakes: ["Pushing too far without support", "Ignoring the counterbreak", "Misusing the extra room"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["space", "maneuvering", "control"],
  },
  {
    slug: "development_lead",
    displayName: "Development Lead",
    shortName: "Development lead",
    summary: "One side has more pieces developed and ready to act.",
    whyItMatters: "A development lead often creates the first tactical or strategic imbalance.",
    commonMistakes: ["Playing slow when ahead in development", "Missing the open lines", "Trading away the lead too early"],
    recommendedDifficulty: ["intro", "beginner"],
    tags: ["opening", "initiative", "tempo"],
  },
  {
    slug: "king_safety_imbalance",
    displayName: "King Safety Imbalance",
    shortName: "King safety",
    summary: "One king is exposed while the other side has a safer shelter.",
    whyItMatters: "King safety often matters more than material when the center opens or files line up.",
    commonMistakes: ["Ignoring the direct attack", "Opening lines at the wrong time", "Failing to keep defenders near the king"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["king_safety", "attack", "initiative"],
  },
  {
    slug: "exchange_sacrifice_compensation",
    displayName: "Exchange Sacrifice Compensation",
    shortName: "Exchange sac",
    summary: "A rook is given up for minor pieces, initiative, or king safety compensation.",
    whyItMatters: "Exchange sacrifices are a common way to convert activity into pressure.",
    commonMistakes: ["Sacrificing without compensation", "Missing the follow-up attack", "Returning material too late"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["sacrifice", "initiative", "compensation"],
  },
  {
    slug: "material_vs_initiative",
    displayName: "Material vs Initiative",
    shortName: "Material vs init",
    summary: "Extra material is weighed against attack, development, and active threats.",
    whyItMatters: "This imbalance decides when to simplify and when to keep the pressure alive.",
    commonMistakes: ["Counting material only", "Ignoring king safety", "Missing forcing lines"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["evaluation", "initiative", "tradeoffs"],
  },
]);
