import { buildDailyConceptDefinitions } from "./dailyConceptTypes";

export const SPECIAL_TECHNIQUE_CONCEPTS = buildDailyConceptDefinitions("special_techniques", [
  {
    slug: "opposition",
    displayName: "Opposition",
    shortName: "Opposition",
    summary: "Kings face each other with a square or move between them to control the route.",
    whyItMatters: "Opposition is the backbone of king activity and pawn endgame play.",
    commonMistakes: ["Counting only material", "Moving the king too soon", "Missing the tempo count"],
    recommendedDifficulty: ["intro", "beginner"],
    tags: ["king", "endgame", "tempo"],
  },
  {
    slug: "triangulation",
    displayName: "Triangulation",
    shortName: "Triangulation",
    summary: "The king or piece wastes a tempo to hand the move back to the opponent.",
    whyItMatters: "Triangulation converts the move count into a weapon and often forces zugzwang.",
    commonMistakes: ["Moving too directly", "Ignoring spare tempos", "Missing the winning opposition change"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["king", "tempo", "endgame"],
  },
  {
    slug: "zugzwang",
    displayName: "Zugzwang",
    shortName: "Zugzwang",
    summary: "Any legal move worsens the position for the side to move.",
    whyItMatters: "Zugzwang is one of the clearest ways to win king and pawn endings.",
    commonMistakes: ["Playing without counting moves", "Ignoring waiting moves", "Missing the squeeze"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["endgame", "tempo", "restriction"],
  },
  {
    slug: "breakthrough",
    displayName: "Breakthrough",
    shortName: "Breakthrough",
    summary: "A pawn break clears the way for a passed pawn or decisive opening of lines.",
    whyItMatters: "Breakthroughs convert structure into direct winning chances.",
    commonMistakes: ["Breaking without support", "Missing the key capture", "Failing to calculate the promotion race"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["pawn_break", "passed_pawn", "attack"],
  },
  {
    slug: "outside_passed_pawn",
    displayName: "Outside Passed Pawn",
    shortName: "Outside passed",
    summary: "A passed pawn on the edge pulls the opponent king away from the center.",
    whyItMatters: "Outside passed pawns often decide the rest of the endgame by force.",
    commonMistakes: ["Ignoring the king pull", "Pushing without support", "Trading the pawn too early"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["endgame", "passed_pawn", "decoy"],
  },
  {
    slug: "shouldering",
    displayName: "Shouldering",
    shortName: "Shouldering",
    summary: "One king uses body placement to cut off the opponent king's route.",
    whyItMatters: "Shouldering is a core king technique for winning opposition and races.",
    commonMistakes: ["Leaving a gap", "Missing the direct shoulder line", "Forgetting the tempo count"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["king", "endgame", "blocking"],
  },
  {
    slug: "corresponding_squares",
    displayName: "Corresponding Squares",
    shortName: "Corresponding",
    summary: "Pairs of squares map to each other in king and pawn endgames.",
    whyItMatters: "Corresponding squares explain why a route wins or draws even when material looks simple.",
    commonMistakes: ["Counting only the next move", "Ignoring opposition changes", "Misreading the mirrored route"],
    recommendedDifficulty: ["expert"],
    tags: ["endgame", "king", "theory"],
  },
  {
    slug: "rook_lift",
    displayName: "Rook Lift",
    shortName: "Rook lift",
    summary: "A rook climbs to the third, fourth, or seventh rank to attack from a new angle.",
    whyItMatters: "Rook lifts turn a quiet rook into an attacking piece without opening new files.",
    commonMistakes: ["Leaving the rook tied to the back rank", "Missing the lift square", "Ignoring the counterinvasion"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["rook", "attack", "mobility"],
  },
  {
    slug: "prophylaxis",
    displayName: "Prophylaxis",
    shortName: "Prophylaxis",
    summary: "A move prevents the opponent's plan before it becomes active.",
    whyItMatters: "Prophylaxis is how strong players keep their own plans safe while limiting the opponent.",
    commonMistakes: ["Only reacting", "Ignoring the opponent's plan", "Overprotecting without purpose"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["planning", "prevention", "strategy"],
  },
  {
    slug: "switching_targets",
    displayName: "Switching Targets",
    shortName: "Switch targets",
    summary: "An attack changes direction toward a better weakness or square.",
    whyItMatters: "Switching targets keeps pressure alive when the first idea is defended.",
    commonMistakes: ["Fixating on one target", "Missing the better weakness", "Allowing the defense to regroup"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["attack", "flexibility", "target"],
  },
  {
    slug: "piece_rerouting",
    displayName: "Piece Rerouting",
    shortName: "Rerouting",
    summary: "A piece takes a new route to reach a better square or role.",
    whyItMatters: "Rerouting is how slow positions become active again without tactical risk.",
    commonMistakes: ["Moving the wrong piece first", "Ignoring the best square", "Forgetting the route is part of the plan"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["maneuvering", "piece_play", "route"],
  },
  {
    slug: "sacrifice_for_activity",
    displayName: "Sacrifice for Activity",
    shortName: "Activity sac",
    summary: "Material is given up so the pieces become more active and the position opens.",
    whyItMatters: "Activity sacrifices often create dynamic compensation even when material looks down.",
    commonMistakes: ["Sacrificing too early", "Ignoring the lead in development", "Missing the follow-up attack"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["sacrifice", "initiative", "activity"],
  },
  {
    slug: "fortress_building",
    displayName: "Fortress Building",
    shortName: "Fortress",
    summary: "A side creates an unbreakable defensive shell that the opponent cannot penetrate.",
    whyItMatters: "Fortresses are the practical way to save hard endgames and avoid losing king activity.",
    commonMistakes: ["Leaving the key square weak", "Trading the wrong defender", "Opening the fortress at the wrong time"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["defense", "endgame", "structure"],
  },
  {
    slug: "tempo_gain",
    displayName: "Tempo Gain",
    shortName: "Tempo gain",
    summary: "A move improves your position while forcing the opponent to react.",
    whyItMatters: "Tempo gains decide who gets to execute the plan first and who gets squeezed.",
    commonMistakes: ["Wasting the extra move", "Ignoring forcing replies", "Not converting tempo into a real threat"],
    recommendedDifficulty: ["intro", "beginner"],
    tags: ["tempo", "initiative", "forcing"],
  },
]);
