import { buildDailyConceptDefinitions } from "./dailyConceptTypes";

export const TACTICAL_IDEA_CONCEPTS = buildDailyConceptDefinitions("tactical_ideas", [
  {
    slug: "fork",
    displayName: "Fork",
    shortName: "Fork",
    summary: "One move attacks two or more targets at once.",
    whyItMatters: "Forks are one of the cleanest ways to win material or force a decisive concession.",
    commonMistakes: ["Missing the tactical target", "Ignoring the king fork", "Playing the move without checking the counter"],
    recommendedDifficulty: ["intro", "beginner"],
    tags: ["tactics", "multiple_attack", "material"],
  },
  {
    slug: "pin",
    displayName: "Pin",
    shortName: "Pin",
    summary: "A piece cannot move because doing so would expose something more valuable behind it.",
    whyItMatters: "Pins freeze defenders and often create tactical or strategic pressure.",
    commonMistakes: ["Missing the pinned piece's value", "Ignoring the unpinning move", "Allowing the pin to be broken for free"],
    recommendedDifficulty: ["intro", "beginner"],
    tags: ["tactics", "immobilization", "pressure"],
  },
  {
    slug: "skewer",
    displayName: "Skewer",
    shortName: "Skewer",
    summary: "A valuable piece is attacked so the more valuable piece behind it becomes exposed.",
    whyItMatters: "Skewers often win material or force the opponent's king into the open.",
    commonMistakes: ["Seeing only the front piece", "Missing the recapture", "Failing to calculate the exposed target"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["tactics", "line_attack", "material"],
  },
  {
    slug: "discovered_attack",
    displayName: "Discovered Attack",
    shortName: "Discovered attack",
    summary: "Moving one piece reveals an attack from another piece behind it.",
    whyItMatters: "Discovered attacks create forcing play without needing an extra tempo.",
    commonMistakes: ["Not seeing the hidden line", "Moving the wrong blocker", "Ignoring the counterattack on the moved piece"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["tactics", "line", "tempo"],
  },
  {
    slug: "double_attack",
    displayName: "Double Attack",
    shortName: "Double attack",
    summary: "A single move creates two separate threats or captures.",
    whyItMatters: "Double attacks force the opponent to choose what to save, and that choice is often losing.",
    commonMistakes: ["Missing the second target", "Seeing only the obvious capture", "Ignoring the forcing check"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["tactics", "pressure", "forcing"],
  },
  {
    slug: "deflection",
    displayName: "Deflection",
    shortName: "Deflection",
    summary: "A defending piece is lured away from the square or piece it was guarding.",
    whyItMatters: "Deflection opens tactical lines and often clears the way for a decisive follow-up.",
    commonMistakes: ["Sacrificing without a follow-up", "Missing the defender's true job", "Ignoring the recapture"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["tactics", "removal", "opening_lines"],
  },
  {
    slug: "decoy",
    displayName: "Decoy",
    shortName: "Decoy",
    summary: "A piece or king is pulled onto a square where it becomes vulnerable.",
    whyItMatters: "Decoys create tactical overloads and force the opponent's hand.",
    commonMistakes: ["Choosing the wrong lure", "Missing the follow-up check", "Allowing the decoy to be ignored"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["tactics", "lure", "forcing"],
  },
  {
    slug: "overloaded_piece",
    displayName: "Overloaded Piece",
    shortName: "Overloaded",
    summary: "One defending piece has too many jobs at once.",
    whyItMatters: "Overloaded defenders collapse when a tactical line removes one of their duties.",
    commonMistakes: ["Not counting the defender's tasks", "Ignoring the tactical switch", "Assuming one piece can hold everything"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["defender", "pressure", "removal"],
  },
  {
    slug: "back_rank_motif",
    displayName: "Back Rank Motif",
    shortName: "Back rank",
    summary: "The enemy king is trapped behind its own pawns and piece barriers.",
    whyItMatters: "Back-rank tactics end games quickly when the escape square is controlled.",
    commonMistakes: ["Ignoring the escape square", "Missing the final rook lift", "Allowing luft"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["mate", "rook", "king"],
  },
  {
    slug: "clearance",
    displayName: "Clearance",
    shortName: "Clearance",
    summary: "A piece or pawn moves away to clear a line, square, or file for another force.",
    whyItMatters: "Clearance is a quiet way to create direct tactical access.",
    commonMistakes: ["Moving without a follow-up", "Clearing the wrong line", "Ignoring the opponent's counter-line"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["tactics", "lines", "sacrifice"],
  },
  {
    slug: "interference",
    displayName: "Interference",
    shortName: "Interference",
    summary: "A move blocks the connection between a defender and the thing it protects.",
    whyItMatters: "Interference often works against rooks, bishops, and queen defenses on open lines.",
    commonMistakes: ["Blocking the wrong line", "Missing the follow-up capture", "Allowing a simple escape move"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["tactics", "blocking", "defense"],
  },
  {
    slug: "zwischenzug",
    displayName: "Zwischenzug",
    shortName: "Zwischenzug",
    summary: "An intermediate move changes the order before the obvious recapture or continuation.",
    whyItMatters: "Zwischenzug is a core habit for forcing play and tactical precision.",
    commonMistakes: ["Playing the automatic recapture", "Ignoring forcing checks", "Missing the stronger in-between move"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["intermediate_move", "forcing", "tempo"],
  },
  {
    slug: "pawn_break",
    displayName: "Pawn Break",
    shortName: "Pawn break",
    summary: "A pawn advance or capture opens the position and changes the pawn structure.",
    whyItMatters: "Pawn breaks decide when a position becomes tactical instead of static.",
    commonMistakes: ["Breaking without support", "Opening the wrong file", "Waiting too long for the break"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["structure", "opening_lines", "timing"],
  },
  {
    slug: "sacrifice_to_open_lines",
    displayName: "Sacrifice to Open Lines",
    shortName: "Open lines",
    summary: "Material is given up to open files, diagonals, or ranks toward the king.",
    whyItMatters: "Open-line sacrifices are the bridge between structure and direct attack.",
    commonMistakes: ["Sacrificing without access", "Missing the queen trade", "Ignoring the defender's escape square"],
    recommendedDifficulty: ["advanced", "expert"],
    tags: ["sacrifice", "attack", "king_safety"],
  },
  {
    slug: "trapped_piece",
    displayName: "Trapped Piece",
    shortName: "Trapped piece",
    summary: "A piece has no good squares and cannot escape without loss.",
    whyItMatters: "Trapped pieces win material without needing a direct capture tactic.",
    commonMistakes: ["Ignoring mobility", "Missing the escape square", "Assuming the piece still has time"],
    recommendedDifficulty: ["beginner", "intermediate"],
    tags: ["mobility", "material", "restriction"],
  },
  {
    slug: "remove_defender",
    displayName: "Remove Defender",
    shortName: "Remove defender",
    summary: "A key defending piece is exchanged, lured away, or overloaded out of the position.",
    whyItMatters: "Removing the right defender can make the whole position collapse.",
    commonMistakes: ["Trading the wrong piece", "Missing the second-order effect", "Ignoring the defended square"],
    recommendedDifficulty: ["intermediate", "advanced"],
    tags: ["tactics", "defense", "target"],
  },
]);
