import assert from "node:assert/strict";

import { buildTrainerDebugSnapshot } from "../../lib/blundr/debug/trainerDebugSnapshot";

export function testStage2TerminalProofRequiredForBranchComplete(): void {
  const blockedSnapshot = buildTrainerDebugSnapshot({
    debugEnabled: true,
    trainerFrameId: 4,
    currentPly: 2,
    currentMoveIndex: 1,
    trainerPhase: "ready_for_user",
    trainerView: "assisted",
    trainingMode: "restricted",
    isUserTurn: true,
    selectedOpeningId: "italian-white",
    selectedLineId: "italian-white",
    selectedOpeningRuntimeAvailable: true,
    runtimeAvailable: true,
    selectedLineCompleteConfirmed: true,
    activeLineName: "Italian Game",
    fen: "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
    expectedMoveResolution: {
      source: "lesson_line",
      reason: "exact_fen_repertoire_node",
      expectedMoveUci: "g1f3",
      expectedMoveSan: "Nf3",
      candidateMoves: [{ uci: "g1f3", san: "Nf3" }],
      lineCursor: 2,
      lineLength: 5,
      shouldTransitionToContinuation: false,
      debug: { exactFenNodeFound: true, transpositionNodeFound: true },
    },
    instructionTargetUci: "g1f3",
    instructionTargetSan: "Nf3",
    instructionTargetPieceType: "n",
    acceptedTargetUci: "g1f3",
    coachMoveUci: "g1f3",
    coachPieceType: "n",
    visualMoveUci: "g1f3",
    visualRecipeMoveUci: "g1f3",
    visualRecipeMoveSan: "Nf3",
    visualRecipeTargetMatchesInstructionTarget: true,
    runtimeBookQueried: true,
    runtimeBookOpeningId: "italian-white",
    runtimeBookPlayKeyBefore: "e2e4,e7e5",
    runtimeBookStatus: "ready",
    runtimeBookCandidateCount: 0,
    runtimeBookBookExhausted: true,
    runtimeBookFallbackUsed: false,
    branchTransitionSurfaceRendered: false,
    branchTransitionReason: null,
    continueFromHereAvailable: false,
    continueFromHereButtonRendered: false,
    trainAgainButtonRendered: false,
    branchCompleteEligible: false,
    branchCompleteReason: null,
    branchCompleteBlockedReason: null,
    branchCompleteLineExhaustedEvidence: false,
    branchCompleteAfterFinalUserMove: false,
    restrictedLineExhaustedOnOpponentTurn: false,
    selectedLineExhausted: false,
    selectedLineExhaustionReason: null,
    selectedLineExhaustionBlockedReason: null,
    exactNodeHasChildren: true,
    hasNextOpponentMove: true,
    hasNextUserMove: true,
    explicitCuratedTerminalNode: false,
    visibleTeachingSurface: {
      owner: "v28_visible_surface",
      mode: "guided_move",
      coach: { shouldRender: true, title: "Nf3 — Develop the knight", body: "Develop the knight.", buttons: [] },
      visual: { lines: [] },
      actions: [],
      safety: { blocked: false, criticalIssues: [] },
      debug: { visibleCoachOwner: "visible_surface_v28", visibleVisualOwner: "visible_surface_v28", visibleActionOwner: "visible_surface_v28" },
    },
    presentationFrame: {
      visual: { shouldRender: true, source: "visible_surface_v28" },
      coach: { shouldRender: true, owner: "intent_first_coach", title: "Nf3 — Develop the knight", body: "Develop the knight.", buttons: [] },
      legacy: {},
    },
    coachDecision: {
      shouldShowCoachCard: true,
      title: "Nf3 — Develop the knight",
      body: "Develop the knight.",
      buttons: [],
      debug: { coachDecisionSource: "live_coach", coachMoveUci: "g1f3", coachPieceType: "n", coachQuality: { qualityScore: 90, targetAligned: true, pieceAligned: true, containsDebugLeak: false } },
    },
    actualCoachCardTitle: "Nf3 — Develop the knight",
    actualCoachCardBody: "Develop the knight.",
    actualCoachCardButtons: [],
    actualCoachCardSource: "surfaceCoachCardDecision",
    actualVisualSource: "visible_surface_v28",
    renderedActionIds: [],
    surfaceActionIds: [],
    renderedVisualPrimitiveCount: 0,
    surfaceVisualPrimitiveCount: 0,
    coachQuality: { qualityScore: 90, qualityScoreSource: "final_rendered", source: "final_rendered", targetAligned: true, pieceAligned: true, usedFallback: false, containsDebugLeak: false },
    eventLog: [],
  } as any);

  assert.equal((blockedSnapshot.frame as any)?.terminalProof?.proven, false);
  assert.equal((blockedSnapshot.frame as any)?.terminalProof?.runtimeBookExhaustionObserved, true);
  assert.equal((blockedSnapshot.frame as any)?.terminalProof?.runtimeBookExhaustionTreatedAsDebugOnly, true);
  assert.equal((blockedSnapshot.frame as any)?.finalSurfaceAuthority?.branchCompleteAllowedByTerminalProof, false);
  assert.equal((blockedSnapshot.frame as any)?.branchTransitionSurfaceRendered, false);
  assert.equal((blockedSnapshot.frame as any)?.continueFromHereAvailable, false);
  assert.equal((blockedSnapshot.coach as any)?.visibleTitle.includes("Line complete"), false);

  const terminalSnapshot = buildTrainerDebugSnapshot({
    debugEnabled: true,
    trainerFrameId: 18,
    trainerPhase: "ready_for_user",
    trainerView: "assisted",
    trainingMode: "restricted",
    isUserTurn: false,
    selectedOpeningId: "italian-white",
    selectedLineId: "italian-white",
    selectedOpeningRuntimeAvailable: true,
    runtimeAvailable: true,
    selectedLineCompleteConfirmed: true,
    fen: "r1bq1rk1/bpp2ppp/p1np1n2/4p3/4P3/1BPP1N2/PP1N1PPP/R1BQR1K1 b - - 16 10",
    expectedMoveResolution: {
      source: "guided_branch_needs_continuation",
      reason: "repertoire_line_exhausted_needs_continuation",
      expectedMoveUci: null,
      expectedMoveSan: null,
      candidateMoves: [],
      lineCursor: 5,
      lineLength: 5,
      shouldTransitionToContinuation: true,
      debug: { exactFenNodeFound: true, transpositionNodeFound: true },
    },
    instructionTargetUci: null,
    instructionTargetSan: null,
    instructionTargetPieceType: null,
    runtimeBookQueried: true,
    runtimeBookOpeningId: "italian-white",
    runtimeBookPlayKeyBefore: "e2e4,e7e5,g1f3,b8c6,f1c4",
    runtimeBookStatus: "ready",
    runtimeBookCandidateCount: 0,
    runtimeBookBookExhausted: true,
    branchTransitionSurfaceRendered: true,
    branchTransitionReason: "restricted_book_exhausted_on_opponent_turn_after_user_move",
    continueFromHereAvailable: true,
    continueFromHereButtonRendered: true,
    trainAgainButtonRendered: true,
    branchCompleteEligible: true,
    branchCompleteReason: "selected_line_exhausted",
    branchCompleteBlockedReason: null,
    branchCompleteLineExhaustedEvidence: true,
    branchCompleteAfterFinalUserMove: true,
    restrictedLineExhaustedOnOpponentTurn: true,
    selectedLineExhausted: true,
    selectedLineExhaustionReason: "selected_line_exhausted",
    selectedLineExhaustionBlockedReason: null,
    exactNodeHasChildren: false,
    hasNextOpponentMove: false,
    hasNextUserMove: false,
    explicitCuratedTerminalNode: false,
    visibleTeachingSurface: {
      owner: "v28_visible_surface",
      mode: "branch_complete",
      coach: { shouldRender: true, title: "Line complete", body: "You finished this training line. Continue from this position or train the line again.", buttons: ["continue_from_here", "restart_line"] },
      visual: { lines: [] },
      actions: [{ kind: "continue_from_here" }, { kind: "restart_line" }],
      safety: { blocked: false, criticalIssues: [] },
      debug: { visibleCoachOwner: "visible_surface_v28", visibleVisualOwner: "visible_surface_v28", visibleActionOwner: "visible_surface_v28" },
    },
    presentationFrame: {
      coach: { shouldRender: true, owner: "branch_transition_surface", title: "Line complete", body: "You finished this training line. Continue from this position or train the line again.", buttons: ["continue_from_here", "restart_line"] },
      visual: { shouldRender: false, source: "none" },
      legacy: {},
    },
    coachDecision: {
      shouldShowCoachCard: true,
      title: "Line complete",
      body: "You finished this training line. Continue from this position or train the line again.",
      buttons: ["continue_from_here", "restart_line"],
      debug: { coachDecisionSource: "branch_transition_surface", coachMoveUci: null, coachPieceType: null, coachQuality: { qualityScore: 90, targetAligned: false, pieceAligned: false, containsDebugLeak: false } },
    },
    actualCoachCardTitle: "Line complete",
    actualCoachCardBody: "You finished this training line. Continue from this position or train the line again.",
    actualCoachCardButtons: ["continue_from_here", "restart_line"],
    actualCoachCardSource: "surfaceCoachCardDecision",
    actualVisualSource: "visible_surface_v28",
    renderedActionIds: ["continue_from_here", "restart_line"],
    surfaceActionIds: ["continue_from_here", "restart_line"],
    renderedVisualPrimitiveCount: 0,
    surfaceVisualPrimitiveCount: 0,
    coachQuality: { qualityScore: 90, qualityScoreSource: "final_rendered", source: "final_rendered", targetAligned: false, pieceAligned: false, usedFallback: false, containsDebugLeak: false },
    eventLog: [],
  } as any);

  assert.equal((terminalSnapshot.frame as any)?.terminalProof?.proven, true);
  assert.equal((terminalSnapshot.frame as any)?.terminalProof?.source, "selected_line_cursor");
  assert.equal((terminalSnapshot.frame as any)?.finalSurfaceAuthority?.branchCompleteAllowedByTerminalProof, true);
  assert.equal((terminalSnapshot.frame as any)?.branchTransitionSurfaceRendered, true);
  assert.equal((terminalSnapshot.frame as any)?.continueFromHereAvailable, true);
  assert.equal((terminalSnapshot.coach as any)?.visibleTitle, "Line complete");
}

testStage2TerminalProofRequiredForBranchComplete();
console.log("stage2TerminalProofRequiredForBranchComplete ok");
