import assert from "node:assert/strict";

import { buildTrainerDebugSnapshot } from "../../lib/blundr/debug/trainerDebugSnapshot";
import { buildTrainerFrameResolution } from "../../lib/blundr/debug/buildTrainerFrameResolution";

export function testStage2SelectedLineIdentityNotCollapsedToOpening(): void {
  const frameResolution = buildTrainerFrameResolution({
    trainerFrameId: 77,
    trainerPhase: "ready_for_user",
    trainerView: "assisted",
    trainingMode: "restricted",
    isUserTurn: true,
    selectedOpeningId: "italian-white",
    selectedLineId: "italian-white:1",
    runtimeBookOpeningId: "italian-white",
    selectedOpeningRuntimeAvailable: true,
    instructionTargetUci: "f1c4",
    instructionTargetSan: "Bc4",
    instructionTargetPieceType: "b",
    coachMoveUci: "f1c4",
    coachPieceType: "b",
    acceptedTargetUci: "f1c4",
    selectedLineCompleteConfirmed: false,
    exactNodeHasChildren: true,
    hasNextOpponentMove: true,
    hasNextUserMove: true,
    validBranchCompleteLatch: false,
    afterFinalUserMove: false,
    runtimeBookBookExhausted: false,
    runtimeBookCandidateCount: 2,
    runtimeBookStatus: "ready",
    visibleTeachingSurface: {
      owner: "v28_visible_surface",
      mode: "guided_move",
      coach: { shouldRender: true, title: "Bc4", body: "Play Bc4.", buttons: [] },
      visual: { lines: [] },
      actions: [],
      safety: { blocked: false, criticalIssues: [] },
    },
    presentationFrame: {
      visual: { shouldRender: true, source: "visible_surface_v28" },
      coach: { shouldRender: true, owner: "intent_first_coach", title: "Bc4", body: "Play Bc4.", buttons: [] },
      legacy: {},
    },
    actualCoachCardTitle: "Bc4",
    actualCoachCardBody: "Play Bc4.",
    actualCoachCardButtons: [],
    actualCoachCardSource: "surfaceCoachCardDecision",
    actualVisualSource: "visible_surface_v28",
    renderedVisualPrimitiveCount: 0,
    surfaceVisualPrimitiveCount: 0,
    coachQuality: { qualityScore: 90, qualityScoreSource: "final_rendered", source: "final_rendered", targetAligned: true, pieceAligned: true, usedFallback: false, containsDebugLeak: false },
    eventLog: [],
  } as any);

  const snapshot = buildTrainerDebugSnapshot({
    debugEnabled: true,
    fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
    trainerFrameId: 77,
    trainerPhase: "ready_for_user",
    trainerView: "assisted",
    trainingMode: "restricted",
    isUserTurn: true,
    selectedOpeningId: "italian-white",
    selectedLineId: "italian-white:1",
    selectedRuntimeLineId: "italian-white:1",
    selectedRuntimeLineKey: "italian-white:1:e2e4,e7e5,g1f3,b8c6,f1c4",
    activeLineName: "Italian Game",
    instructionTargetUci: "f1c4",
    instructionTargetSan: "Bc4",
    instructionTargetPieceType: "b",
    coachMoveUci: "f1c4",
    coachPieceType: "b",
    acceptedTargetUci: "f1c4",
    runtimeDataSource: "local_crawled_package",
    runtimePackageId: "stage2-21-opening-stepdown-runtime-v1",
    openingCount: 21,
    visibleOpeningCount: 21,
    runtimeBookQueried: true,
    runtimeBookOpeningId: "italian-white",
    runtimeBookPlayKeyBefore: "e2e4,e7e5,g1f3,b8c6,f1c4",
    runtimeBookStatus: "ready",
    runtimeBookCandidateCount: 2,
    runtimeBookTopCandidateUci: "f8c5",
    runtimeBookTopCandidateSan: "Bc5",
    runtimeBookTopCandidateRank: 1,
    runtimeBookTopCandidateGames: 61569824,
    runtimeBookTopCandidatePlayPct: 0.33771,
    runtimeBookBookExhausted: false,
    runtimeBookFallbackUsed: false,
    runtimeBookFallbackAuthority: null,
    lineSelectionMode: "runtime_weighted_line",
    lineSelectionSource: "local_runtime_package",
    lineSelectionWeighted: true,
    lineSelectionContentGated: false,
    lineSelectionRuntimeBacked: true,
    lineSelectionEligibleCount: 2,
    lineSelectionEligibleLineIds: ["italian-white:0", "italian-white:1"],
    lineSelectionEligibleLineKeys: ["italian-white:0:e2e4,e7e5,g1f3,b8c6", "italian-white:1:e2e4,e7e5,g1f3,b8c6,f1c4"],
    lineSelectionRecentLineKeys: ["italian-white:0:e2e4,e7e5,g1f3,b8c6"],
    lineSelectionBlockedRecentLineKeys: ["italian-white:0:e2e4,e7e5,g1f3,b8c6"],
    lineSelectionVariationReason: "recent_line_keys_excluded",
    lineSelectionSeed: "stage2-session-1",
    selectedRuntimeLineId: "italian-white:1",
    selectedRuntimeLineKey: "italian-white:1:e2e4,e7e5,g1f3,b8c6,f1c4",
    selectedRuntimeLineIndex: 1,
    selectedRuntimeLinePlayKey: "e2e4,e7e5,g1f3,b8c6,f1c4",
    selectedRuntimeLinePlaySequenceUci: ["e2e4", "e7e5", "g1f3", "b8c6", "f1c4"],
    visibleTeachingSurface: {
      owner: "v28_visible_surface",
      mode: "guided_move",
      coach: { shouldRender: true, title: "Bc4", body: "Play Bc4.", buttons: [] },
      visual: { lines: [] },
      actions: [],
      safety: { blocked: false, criticalIssues: [] },
      debug: { visibleCoachOwner: "visible_surface_v28", visibleVisualOwner: "visible_surface_v28", visibleActionOwner: "visible_surface_v28" },
    },
    presentationFrame: {
      visual: { shouldRender: true, source: "visible_surface_v28" },
      coach: { shouldRender: true, owner: "intent_first_coach", title: "Bc4", body: "Play Bc4.", buttons: [] },
      legacy: {},
    },
    coachDecision: { shouldShowCoachCard: true, title: "Bc4", body: "Play Bc4.", buttons: [], debug: { coachDecisionSource: "live_coach", coachMoveUci: "f1c4", coachPieceType: "b", coachQuality: { qualityScore: 90, targetAligned: true, pieceAligned: true, containsDebugLeak: false } } },
    actualCoachCardTitle: "Bc4",
    actualCoachCardBody: "Play Bc4.",
    actualCoachCardButtons: [],
    actualCoachCardSource: "surfaceCoachCardDecision",
    actualVisualSource: "visible_surface_v28",
    visualRecipeMoveUci: "f1c4",
    visualRecipeTargetMatchesInstructionTarget: true,
    visualMoveUci: "f1c4",
    renderedActionIds: [],
    surfaceActionIds: [],
    renderedVisualPrimitiveCount: 0,
    surfaceVisualPrimitiveCount: 0,
    coachQuality: { qualityScore: 90, qualityScoreSource: "final_rendered", source: "final_rendered", targetAligned: true, pieceAligned: true, usedFallback: false, containsDebugLeak: false },
    eventLog: [],
    trainerFrameResolution: frameResolution,
  } as any);

  assert.equal(frameResolution.openingIdentity?.selectedOpeningId, "italian-white");
  assert.equal(frameResolution.openingIdentity?.selectedOpeningId, frameResolution.openingIdentity?.canonicalSelectedOpeningId);
  assert.equal((snapshot.frame as any)?.selectedLineId, "italian-white:1");
  assert.equal((snapshot.runtime as any)?.selectedOpeningId, "italian-white");
  assert.equal((snapshot.runtime as any)?.selectedRuntimeLineId, "italian-white:1");
  assert.equal((snapshot.runtime as any)?.selectedRuntimeLineKey, "italian-white:1:e2e4,e7e5,g1f3,b8c6,f1c4");
  assert.notEqual((snapshot.runtime as any)?.selectedRuntimeLineId, (snapshot.runtime as any)?.selectedOpeningId);
}

testStage2SelectedLineIdentityNotCollapsedToOpening();
console.log("stage2SelectedLineIdentityNotCollapsedToOpening ok");
