"use client";
import { useEffect, useRef } from "react";
import { MarketingButton } from "../shared/MarketingButton";
import { heroData } from "./heroData";
import styles from "./BlundrHero.module.css";

export function BlundrHero({ tempoImageSrc }: { tempoImageSrc: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const stageRef = useRef<HTMLDivElement>(null); const spriteRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const canvas=canvasRef.current,stage=stageRef.current,sprite=spriteRef.current;if(!canvas||!stage||!sprite)return;const ctx=canvas.getContext("2d");if(!ctx)return;let raf=0,dpr=1,running=true;const draw=()=>{if(!running)return;const rect=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);const top=rect.height*.1,bottom=rect.height*.88;for(let r=0;r<8;r++)for(let f=0;f<8;f++){const t=(r+.5)/8,w=rect.width*(.48+.41*Math.pow(t,.82)),x=rect.width*.52-w/2+w*(f+.5)/8,y=top+(bottom-top)*Math.pow(t,.82),size=w/8;ctx.fillStyle=(r+f)%2?"#76a94c":"#edf4d1";ctx.beginPath();ctx.moveTo(x-size/2,y-size*.46);ctx.lineTo(x+size/2,y-size*.46);ctx.lineTo(x+size/2,y+size*.46);ctx.lineTo(x-size/2,y+size*.46);ctx.closePath();ctx.fill();}raf=requestAnimationFrame(draw)};const move=(event:PointerEvent)=>{const rect=stage.getBoundingClientRect();const x=Math.max(12,Math.min(88,(event.clientX-rect.left)/rect.width*100));const y=Math.max(25,Math.min(78,(event.clientY-rect.top)/rect.height*100));sprite.style.left=`${x}%`;sprite.style.top=`${y}%`};stage.addEventListener("pointermove",move);const resize=new ResizeObserver(()=>{if(!running)draw()});resize.observe(canvas);const visibility=new IntersectionObserver(([entry])=>{running=entry.isIntersecting;if(running){cancelAnimationFrame(raf);draw()}else cancelAnimationFrame(raf)},{rootMargin:"220px 0px",threshold:.08});visibility.observe(stage);draw();return()=>{running=false;cancelAnimationFrame(raf);stage.removeEventListener("pointermove",move);resize.disconnect();visibility.disconnect()}},[]);
  return <section id={heroData.id} className={styles.hero} aria-labelledby="blundr-hero-title"><div className={styles.copy}><p className={styles.eyebrow}>{heroData.eyebrow}</p><h1 id="blundr-hero-title">{heroData.title}</h1><p className={styles.lead}>{heroData.body}</p><div className={styles.ctaRow}><MarketingButton href={heroData.signupHref}>Start training free</MarketingButton><a className={styles.secondary} href="#training-demo">Explore training</a></div></div><div ref={stageRef} className={styles.stage} aria-label="Interactive animated chessboard with Tempo"><canvas ref={canvasRef} aria-hidden="true"/><div ref={spriteRef} className={styles.tempo}><div className={styles.life}><img src={tempoImageSrc} alt=""/><i className={styles.left}/><i className={styles.right}/></div></div></div></section>;
}
